# Generated by Django 3.2.21 on 2023-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
