# Generated by Django 3.2.21 on 2023-09-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employerprofile_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='job_description',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='recruiting_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='technologies_used',
            field=models.TextField(blank=True),
        ),
    ]
