# Generated by Django 3.2.21 on 2023-09-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_jobpostcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostComment',
        ),
    ]
