# Generated by Django 3.2.21 on 2023-11-21 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0002_auto_20231121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 17, 24, 49, 727555, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=10),
            preserve_default=False,
        ),
    ]
