# Generated by Django 3.2.21 on 2023-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0003_auto_20231121_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateField(default='2023-11-22 23:59:59'),
        ),
    ]
